### ISSUE TITLE
[Bug]: Testnet p2wpkh/bech32 address not working

### ISSUE THREAD

**Issue by kyranjamie** [LedgerHQ/ledger-live#2284]
### Impacted Library name

@ledgerhq/hw-app-btc

### Impacted Library version

9.1.1

### Describe the bug

Tested on Nano S Plus, Bitcoin app `v2.0.6`. Latest firmware.

When calling the `getWalletPublicKey` method, I'm unable to pull a testnet derivation path's public key.

Consider this code, to pull a mainnet address:

```ts
btn.addEventListener('click', async () => {
  const { app, transport } = await connectBitcoinLedgerApp();
  const resp = await app.getWalletPublicKey("84'/0'/0'/0/0", { format: 'bech32' });
  console.log(resp);
  await transport.close();
});
```

Outcome: ✅ device returns valid response

The same again but using a testnet derivation path:

```ts
btn.addEventListener('click', async () => {
  const { app, transport } = await connectBitcoinLedgerApp();
  const resp = await app.getWalletPublicKey("84'/1'/0'/0/0", { format: 'bech32' });
  console.log(resp);
  await transport.close();
});
```

Outcome: ❌ error thrown.

```js
{
    "name": "TransportStatusError",
    "message": "Ledger device: UNKNOWN_ERROR (0x6a82)",
    "stack": "Error\n    at new TransportStatusError (webpack-internal:///./node_modules/@ledgerhq/hw-transport/node_modules/@ledgerhq/errors/lib-es/index.js:365:18)\n    at TransportWebUSB.eval (webpack-internal:///./node_modules/@ledgerhq/hw-transport/lib-es/Transport.js:130:39)\n    at step (webpack-internal:///./node_modules/@ledgerhq/hw-transport/lib-es/Transport.js:44:23)\n    at Object.eval [as next] (webpack-internal:///./node_modules/@ledgerhq/hw-transport/lib-es/Transport.js:25:53)\n    at fulfilled (webpack-internal:///./node_modules/@ledgerhq/hw-transport/lib-es/Transport.js:16:58)",
    "statusCode": 27266,
    "statusText": "UNKNOWN_ERROR"
}
```

### Expected behavior

Device/js library should return a correctly formed testnet btc address.

**Comment by adrienlacombe-ledger** [comment]
answered on Discord

**Comment by bigspider** [comment]
For anyone reaching here in the future: the new Bitcoin app is more restrictive on the allowed derivation paths; therefore the Bitcoin Testnet app has to be used when using testnet derivation paths.
