### ISSUE TITLE
[Bug]: Ledger Nano X: `TransportStatusError` thrown if `LedgerEthTransactionResolution` is passed into signTransaction on other network than `homestead` for NFTs

### ISSUE THREAD

**Issue by xdzurman** [LedgerHQ/ledger-live#2458]
### Impacted Library name

@ledgerhq/hw-app-eth

### Impacted Library version

6.30.5

### Describe the bug

For any ERC721 or ERC1155 NFTs, if transactionResolution is passed into `signTransaction` (goerli network), an error is returned instantly, completely identical to the error you get if the user explicitly declines the transaction:
```
{
        "name": "TransportStatusError",
        "message": "Ledger device: Condition of use not satisfied (denied by the user?) (0x6985)",
        "stack": "Error\n    at new TransportStatusError (webpack-internal:///../node_modules/@ledgerhq/errors/lib-es/index.js:367:18)\n    at TransportWebHID.eval (webpack-internal:///../node_modules/@ledgerhq/hw-transport/lib-es/Transport.js:131:39)\n    at step (webpack-internal:///../node_modules/@ledgerhq/hw-transport/lib-es/Transport.js:45:23)\n    at Object.eval [as next] (webpack-internal:///../node_modules/@ledgerhq/hw-transport/lib-es/Transport.js:26:53)\n    at fulfilled (webpack-internal:///../node_modules/@ledgerhq/hw-transport/lib-es/Transport.js:17:58)\n    at patchedCallback (<anonymous>:132:45)",
        "statusCode": 27013,
        "statusText": "CONDITIONS_OF_USE_NOT_SATISFIED"
    }
```

The code for getting resolution is 
```
import {ledgerService} from '@ledgerhq/hw-app-eth'
const resolution = await ledgerService.resolveTransaction(
      serializedTransaction,
      {},
      {nft: true},
)

const {v, r, s} = await ledger.signTransaction(
        derivationPath,
        serializedTransaction,
        resolution,
)
```

### Expected behavior

The built-in resolution returns a normal looking response from `https://nft.api.live.ledger.com/v1/ethereum`, but it crashes somewhere down the road. If the resolution is okay, I'd expect the device to correctly show NFT data (clear signing, no blind signing enabled). If it is not valid, I'd expect it not to crash on this random error, but say something along the lines that current network is not supported for clear signing.

**Comment by lambertkevin** [comment]
Hi @xdzurman ! 
Thanks for the report, I'll have a look ASAP 👌

**Comment by lambertkevin** [comment]
@xdzurman Could you please provided a serialized transaction to reproduce your issue please ? It would help a lot 👍

**Comment by xdzurman** [comment]
```
{
    "resolution": {
        "nfts": [
            "01010d4379616e2050656e6775696e73025bdf730eec33b70afcf63c3fe5bdc916f9aeef0000000000000005010147304502210087a6c13187b65ddae5bce493a90b870e7cd1c128a5f59fcbcc528b6ef60a5c1302207cc54140fed6c5a5f60bd44796935a9366d08ab91daac5914ad0cdc27ffe9ce5"
        ],
        "erc20Tokens": [],
        "externalPlugin": [],
        "plugin": [
            "010106455243373231025bdf730eec33b70afcf63c3fe5bdc916f9aeefb88d4fde00000000000000050201483046022100c3ea8b6a6b1afc6b237c196a9d5fad92cbe6bcdc03e9c461a1b084d7f18e9cd2022100c075d4f2226fa8e5dd0050b8e9d9c137daeda855c33238937d68ed030c9f7fc1"
        ]
    },
    "unsignedTransaction": {
        "data": "0xb88d4fde0000000000000000000000006fac4d18c912343bf86fa7049364dd4e424ab9c00000000000000000000000006fac4d18c912343bf86fa7049364dd4e424ab9c000000000000000000000000000000000000000000000000000000000000000ee00000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000000",
        "to": "0x025bdf730EeC33B70AFCF63c3fE5Bdc916F9aeeF",
        "gasLimit": {
            "type": "BigNumber",
            "hex": "0xe238"
        },
        "maxFeePerGas": {
            "type": "BigNumber",
            "hex": "0xa5b36f00"
        },
        "maxPriorityFeePerGas": {
            "type": "BigNumber",
            "hex": "0x52412100"
        },
        "from": "0x6Fac4D18c912343BF86fa7049364Dd4E424Ab9C0",
        "type": 2,
        "nonce": 8,
        "chainId": 5
    },
    "serializedTransaction": "02f8cc0508845241210084a5b36f0082e23894025bdf730eec33b70afcf63c3fe5bdc916f9aeef80b8a4b88d4fde0000000000000000000000006fac4d18c912343bf86fa7049364dd4e424ab9c00000000000000000000000006fac4d18c912343bf86fa7049364dd4e424ab9c000000000000000000000000000000000000000000000000000000000000000ee00000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000000c0"
}
```

**Comment by lambertkevin** [comment]
Ok so it looks like we have a chain ID check on the Ethereum app for plugins (NFT support being one of them). 
So if you want to test with goerli, you'll need to use the Ethereum Goerli nano app (available in Ledger Live by activating the developer mode in "Experimental Features"). 

I'm working with the firmware team to find a solution to remove that check in order for the Ethereum app to clear sign any chain ID. I'll keep up posted 👌
