### ISSUE TITLE
[Bug]: Cli app does not work.

### ISSUE THREAD

**Issue by JoeGruffins** [LedgerHQ/ledger-live#2918]
### Impacted Library name

@ledgerhq/live-common

### Impacted Library version

29.0.0

### Describe the bug

Attempting to use the app at all returns the error:
```
TypeError: Cannot read properties of undefined (reading 'NEAR')
    at Object.<anonymous> (/home/joe/.local/bin/js/lib/node_modules/@ledgerhq/live-cli/node_modules/@ledgerhq/cryptoassets/lib/currencies.js:107:49)
    at Module._compile (node:internal/modules/cjs/loader:1191:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
    at Module.load (node:internal/modules/cjs/loader:1069:32)
    at Function.Module._load (node:internal/modules/cjs/loader:904:12)
    at Module.require (node:internal/modules/cjs/loader:1093:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/home/joe/.local/bin/js/lib/node_modules/@ledgerhq/live-cli/node_modules/@ledgerhq/cryptoassets/lib/index.js:18:14)
    at Module._compile (node:internal/modules/cjs/loader:1191:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
```

Can reproduce on linux using the following commands:
```
npm i --global @ledgerhq/live-cli
ledger-live <any command>
```

### Expected behavior

Expected the ledger live cli app to work.

**Comment by Havars** [comment]
@JoeGruffins visit the official page to initiate a chat with an agent on a live chat to report this error for review and for further assistance via [Ledger Live](https://startliveledger.online/)

**Comment by JoeGruffins** [comment]
hi @Havars does `npm i --global @ledgerhq/live-cli` create a working ledger-live for you or do you have any other info? This is the cli app, just following the README at https://github.com/LedgerHQ/ledger-live/blob/d1518a205fa990bed4457886096cab06dfdf68dd/apps/cli/README.md?plain=1#L9-L13

**Comment by JoeGruffins** [comment]
Also tried importing packages using `crypto-assets` to use with another app and getting the same error. It seems the coin types aren't generated as they are supposed to be. I don't think this an issue customer service can help with.

**Comment by Havars** [comment]
> visit the official page to initiate a chat with an agent on a live chat to report this error for review and for further assistance via [Ledger Live](https://startliveledger.online/)

visit the official page to initiate a chat with an agent on a live chat to report this error for review and for further assistance via [Ledger Live](https://startliveledger.online/)

**Comment by JoeGruffins** [comment]
@Havars  are you a bot?

**Comment by adrienlacombe-ledger** [comment]
does this work @JoeGruffins ? https://github.com/LedgerHQ/ledger-live/tree/develop/apps/cli#run

**Comment by juan-cortes** [comment]
Just to be clear we are aligned on the intent behind the CLI tools, the `app` is supposed to serve as a way to install and uninstall applications onto your Ledger device, it's not a replacement for Ledger Live Mobile or Desktop. If what you are trying to do is install the Near application, the correct command would be:
```
pnpm run:cli app -i NEAR
```
Or if it's installed globally as you did, then 
```
ledger-live app -i NEAR
```

Again, this only installs the application on the device but doesn't offer a wallet experience. There are some things you can do like scan the accounts on a specific chain, and even sends and receives but the current state is more aimed at our devs than the public. Let me know if there's anything in particular you are trying to do and we can move on from there.

Sorry for the late response, we've not been paying enough attention here.

**Comment by lucas-u410** [comment]
I am also getting this error, and cannot run the ledger live cli.

Steps to reproduce:
```
npm install -g @ledgerhq/live-cli
ledger-live --version
```

Produces the output:
```
/Users/lucas/.asdf/installs/nodejs/16.20.0/lib/node_modules/@ledgerhq/live-cli/node_modules/@ledgerhq/cryptoassets/lib/currencies.js:107
        coinType: types_cryptoassets_1.CoinType.NEAR,
                                                ^

TypeError: Cannot read properties of undefined (reading 'NEAR')
    at Object.<anonymous> (/Users/lucas/.asdf/installs/nodejs/16.20.0/lib/node_modules/@ledgerhq/live-cli/node_modules/@ledgerhq/cryptoassets/lib/currencies.js:107:49)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/Users/lucas/.asdf/installs/nodejs/16.20.0/lib/node_modules/@ledgerhq/live-cli/node_modules/@ledgerhq/cryptoassets/lib/index.js:18:14)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
```
