### ISSUE TITLE
[Bug]: algorand.sign() returns 66 bytes signature, algosdk expects 64 bytes signature

### ISSUE THREAD

**Issue by surhud004** [LedgerHQ/ledger-live#3798]
### Impacted Library name

@ledgerhq/hw-app-algorand

### Impacted Library version

6.27.15

### Describe the bug

I am trying to sign an Algorand multi-sig transaction with the Ledger Nano X (Algorand app `v2.1.7`) but when I am trying to append the raw signature, it returns an error stating: `Error: Cannot add multisig signature. Signature is not of the correct length.`
Here's the code snippet to generate the multi-sig transaction with `algosdk (v2.4.0)`:
It's a payment transaction, sending 1 Algo from a multi-sig wallet to a recipient wallet -
```
const params = await algodClient.getTransactionParams().do()
const txn = algosdk.makePaymentTxnWithSuggestedParams(
    multisigSenderAddress,
    recipientAddress,
    1000000,
    undefined,
    undefined,
    params
)

const rawMultisigTxn = algosdk.createMultisigTransaction(txn, multisigParams)
console.log(Buffer.from(rawMultisigTxn).toString('hex'))
```

Then, I sign the transaction with Ledger, passing the hex encoded txn to `algorand.sign()` -
```
TransportWebUSB.create().then(async (transport) => {
    listen((log) => console.log(log));
    const algorand = new Algorand(transport);
    const address = await algorand.getAddress(derivationPath);
    console.info(address.address);
    const signedTxn = await algorand.sign(derivationPath, txn);
    console.log(Buffer.from(signedTxn.signature).toString("hex"));
});
```

Finally, trying to append the signature to the raw multi-sig txn -
```
const signedRawTxn = algosdk.appendSignRawMultisigSignature(rawMultisigTxn, multisigParams, publicKey, Uint8Array.from(signedTxn.signature)).blob
```

The `appendSignRawMultisigSignature` throws error -
```
Error: Cannot add multisig signature. Signature is not of the correct length.
    at MultisigTransaction.partialSignWithMultisigSignature (...\node_modules\algosdk\dist\cjs\multisig.js:167:19)
    at Object.appendSignRawMultisigSignature (...\node_modules\algosdk\dist\cjs\multisig.js:381:39)
```

The `algosdk` validates the signature length using `tweetnacl` which returns 64 bytes - [here]( https://github.com/algorand/js-algorand-sdk/blob/afe67b091747b8811a7ce9a52c8329dfd004168f/src/nacl/naclWrappers.ts#L21)

How do I resolve this? Is there any other method to sign multi-sig transactions with `@ledgerhq/hw-app-algorand`?

References: 
- [createMultisigTransaction](https://algorand.github.io/js-algorand-sdk/functions/createMultisigTransaction.html)
- [appendSignRawMultisigSignature](https://algorand.github.io/js-algorand-sdk/functions/appendSignRawMultisigSignature.html)

### Expected behavior

To be able to append multi-sig signature from Ledger.

### Additional context

I was able to connect and retrieve Algorand wallet address from the Ledger via USB. I was also able to sign and submit a non-multisig payment transaction with Ledger using `algosdk.encodeUnsignedTransaction(rawTxn)`.

**Comment by surhud004** [comment]
Issue resolved. Fixed the signature logic on my end. Thanks.
