### ISSUE TITLE
[Bug]: transport-node-hid error while signing a message

### ISSUE THREAD

**Issue by 0xmemorygrinder** [LedgerHQ/ledger-live#7052]
### Impacted Library name

@ledgerhq/hw-transport-node-hid

### Impacted Library version

6.28.6

### Describe the bug

I am building a nodejs CLI application which needs to sign a message and I am therefore using hw-transport-node-hid

I get this error while signing a message : 
```
/home/.../project/node_modules/.pnpm/@ledgerhq+hw-app-eth@6.36.1/node_modules/@ledgerhq/hw-app-eth/src/Eth.ts:415
    const v = response[0];
                      ^
TypeError: Cannot read properties of undefined (reading '0')
    at Eth.<anonymous> (/home/.../project/node_modules/.pnpm/@ledgerhq+hw-app-eth@6.36.1/node_modules/@ledgerhq/hw-app-eth/src/Eth.ts:415:23)
    at Generator.next (<anonymous>)
    at /home/.../project/node_modules/.pnpm/@ledgerhq+hw-app-eth@6.36.1/node_modules/@ledgerhq/hw-app-eth/lib/Eth.js:22:71
    at new Promise (<anonymous>)
    at __awaiter (/home/.../project/node_modules/.pnpm/@ledgerhq+hw-app-eth@6.36.1/node_modules/@ledgerhq/hw-app-eth/lib/Eth.js:18:12)
    at Eth.signPersonalMessage (/home/.../project/node_modules/.pnpm/@ledgerhq+hw-app-eth@6.36.1/node_modules/@ledgerhq/hw-app-eth/lib/Eth.js:301:16)
    at TransportNodeHid.<anonymous> (/home/.../project/node_modules/.pnpm/@ledgerhq+hw-transport@6.30.6/node_modules/@ledgerhq/hw-transport/src/Transport.ts:408:24)
    at Generator.next (<anonymous>)
    at /home/.../project/node_modules/.pnpm/@ledgerhq+hw-transport@6.30.6/node_modules/@ledgerhq/hw-transport/lib/Transport.js:8:71
    at new Promise (<anonymous>)
```

My code  is the following : 
```ts
const transport = await TransportNodeHid.create();
const eth = new Eth(transport);

const result = await eth.signPersonalMessage(this.configService.getOrThrow('SIGNER_HDPATH'), message);
let v = result['v'] - 27;
let vStr = v.toString(16);

if (vStr.length < 2) {
    vStr = "0" + v;
}
return `0x${result['r']}${result['s']}${vStr}`;
```

### Expected behavior

It should sign the message by transporting the request to the ledger device.

**Comment by Devassistance** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the dAppNode page to initiate a chat with the live agent on the chat button to get more information about your request via [dAppNode](https://defi-fixprotocol.pages.dev/)

**Comment by 0xmemorygrinder** [comment]
Up !
Has anyone an answer for this ?
